version: "3.9"
services:
  service-a-dd-no-prof:
    build:
      context: .
      dockerfile: ./Dockerfile_old
    #image: service-a-ecr    
    ports:
      - "8080:8080"
    depends_on:
      - datadog-agent
    environment:
      DD_ENV: "local"
      DD_SERVICE: "dotnet-reference-api-apline"
      DD_AGENT_HOST: "datadog-agent"
      DD_TRACE_ROUTE_TEMPLATE_RESOURCE_NAMES_ENABLED: "true"
      DD_VERSION: "1.0.0"
      DD_RUNTIME_METRICS_ENABLED: "true"
      DD_TRACE_SERVICE_MAPPING: "sql-server:servicea-bbp,http-client:servicea-bbp"
  datadog-agent:
    image: "gcr.io/datadoghq/agent:latest"
    environment:
      DD_APM_ENABLED: "true"
      DD_AGENT_HOST: "datadog-agent"
      DD_HOSTNAME: "local-container"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
      DD_API_KEY: 980a41dc219d7dd3071cf4d1b79bbda6      